### PR TITLE
Add table scope to where statements

### PR DESCRIPTION
**Pull request by tomprats**
I was running into a problem using a join statement on `ancestors`. By using the `table_name` on the where statements, you'll be able to use `joins` more freely!

Let me know your thoughts on merging this in!

Thanks,
Tom

### CODE REVIEW

**Comment by tomekw** [comment]
Looks great! :+1: 

@cfabianski ?

**Comment by cfabianski** [comment]
Yup looks good :star:

**Comment by tomprats** [comment]
Think you guys could merge this in? I was hoping to go back to using the gem directly instead of a fork

**Comment by tomprats** [comment]
@cfabianski @tomekw Anything holding this back from being merged?

**Comment by cfabianski** [comment]
@tomprats I will merge that soon. Need to fix the CI first (which shouldn't take long)

**Comment by cfabianski** [comment]
1.0.0 is released with this change included!

**Comment by tomprats** [comment]
@cfabianski Thanks a lot! Great work on this project

**Pull request merged**
