### PR TITLE
Updating `pg` dependency to allow 1.x

### PR DESCRIPTION
**Pull request by yuri-zubov**

### CODE REVIEW

**Comment by borisd** [comment]
Could this be merged? This also solves https://github.com/cfabianski/ltree_hierarchy/issues/27

**Comment by doncuomo** [comment]
@yuri-zubov  @borisd Could this be merged?

**Comment by borisd** [comment]
I have been using successfully for a while now, with no issues.

**Comment by doncuomo** [comment]
> I have been using successfully for a while now, with no issues.
Alright thanks.

I've started using it aswell. @cfabianski could this be merged?

**Pull request merged**
