### PR TITLE
Rails 5 belongs_to should use optional: true.

### PR DESCRIPTION
**Pull request by CUnknown**
based on https://github.com/amerine/acts_as_tree/pull/46/files

### CODE REVIEW

**Comment by tomekw** [comment]
⭐️ works for me, @cfabianski ?

**Comment by cfabianski** [comment]
Hi @CUnknown, sorry it took me so long to get back to you.
Could you please resolve the conflict? 
I'll get this merged straight after.

**Comment by cfabianski** [comment]
@CUnknown I'll check the build and I'll get it merged down asap. Thanks!

**Comment by swapnilchincholkar** [comment]
@cfabianski Seems this one not yet merged. Will you please do it?

**Comment by okcscott** [comment]
@cfabianski is there an estimate for when this will get merged?

**Pull request merged**
